{{- if and .Values.ldap.enabled (not .Values.ldap.admin.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak-mas.fullname" . }}-ldap-admin
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: openldap
type: Opaque
stringData:
  LDAP_ADMIN_PASSWORD: {{ .Values.ldap.admin.password | quote }}
{{- end }}
