{{- if and .Values.realm.import.enabled (not .Values.realm.import.configMapName) }}
{{- $realmFile := .Values.realm.exportPath | default "files/maximo-realm.json" -}}
{{- $realmContent := required (printf "realm export file %s is required when realm import is enabled" $realmFile) (.Files.Get $realmFile) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak-mas.realmConfigMapName" . }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: keycloak-realm
data:
  {{ .Values.realm.import.filename }}: |-
{{ tpl $realmContent . | indent 4 }}
{{- end }}
