apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: mas-iam-operator.v0.1.0
  namespace: placeholder
  annotations:
    olm.operatorframework.io/upgrade-safe: "true"
    alm-examples: |
      [
        {
          "apiVersion": "k8s.keycloak.org/v2alpha1",
          "kind": "Keycloak",
          "metadata": {
            "name": "mas-iam"
          },
          "spec": {
            "instances": 1,
            "hostname": {
              "hostname": "keycloak.mas-iam.svc.cluster.local",
              "strict": false
            }
          }
        }
      ]
spec:
  displayName: MAS IAM Bootstrap Operator
  description: |
    Installs the upstream Keycloak Operator and applies MAS IAM defaults
    (PostgreSQL, realm import, optional OpenLDAP). Acts as a thin wrapper so
    teams can deploy the stack with a single Operator installation.
  maturity: alpha
  version: 0.1.0
  provider:
    name: MAS IAM Toolkit
  keywords:
    - keycloak
    - mas
    - identity
  maintainers:
    - name: MAS IAM
      email: you@example.com
  links:
    - name: Project Repository
      url: https://example.com/mas-iam
  install:
    strategy: deployment
    spec:
      clusterPermissions: []
      permissions:
        - serviceAccountName: mas-iam-bootstrap
          rules:
            - apiGroups: [""]
              resources: ["secrets", "services"]
              verbs: ["get", "list", "watch", "create", "update", "patch"]
            - apiGroups: ["apps"]
              resources: ["deployments", "statefulsets"]
              verbs: ["get", "list", "watch", "create", "update", "patch"]
            - apiGroups: ["operators.coreos.com"]
              resources: ["operatorgroups", "subscriptions"]
              verbs: ["get", "list", "watch", "create", "update", "patch"]
            - apiGroups: ["k8s.keycloak.org"]
              resources: ["keycloaks", "keycloakrealmimports"]
              verbs: ["get", "list", "watch", "create", "update", "patch"]
      deployments:
        - name: mas-iam-bootstrap
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: mas-iam-bootstrap
            template:
              metadata:
                labels:
                  app: mas-iam-bootstrap
              spec:
                serviceAccountName: mas-iam-bootstrap
                containers:
                  - name: bootstrap
                    image: quay.io/your-org/mas-iam-bootstrap:0.1.0
                    imagePullPolicy: IfNotPresent
                    env:
                      - name: TARGET_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: UPSTREAM_CHANNEL
                        value: fast
                      - name: UPSTREAM_SOURCE
                        value: community-operators
                      - name: UPSTREAM_SOURCE_NS
                        value: openshift-marketplace
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: true
    - type: MultiNamespace
      supported: false
    - type: AllNamespaces
      supported: false
